// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_PkmsxduB9rYVCPaA_A_xFxilzu5Kt5E',
    appId: '1:667537455051:web:37198ecc0d558b8af9a84e',
    messagingSenderId: '667537455051',
    projectId: 'tp3-420-5n6',
    authDomain: 'tp3-420-5n6.firebaseapp.com',
    storageBucket: 'tp3-420-5n6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BQWpdZ5E35Kt9O5M2JaIPe3d0t5aOv4',
    appId: '1:667537455051:android:eef6fced0992995df9a84e',
    messagingSenderId: '667537455051',
    projectId: 'tp3-420-5n6',
    storageBucket: 'tp3-420-5n6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOWVRHb9jBv_WTrO1yQqvwxtrf0jcD1Wg',
    appId: '1:667537455051:ios:f12d7bf8db3781f9f9a84e',
    messagingSenderId: '667537455051',
    projectId: 'tp3-420-5n6',
    storageBucket: 'tp3-420-5n6.appspot.com',
    iosClientId: '667537455051-5v57ajepv1tju7u6292fo5jb8t0b1f1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOWVRHb9jBv_WTrO1yQqvwxtrf0jcD1Wg',
    appId: '1:667537455051:ios:f12d7bf8db3781f9f9a84e',
    messagingSenderId: '667537455051',
    projectId: 'tp3-420-5n6',
    storageBucket: 'tp3-420-5n6.appspot.com',
    iosClientId: '667537455051-5v57ajepv1tju7u6292fo5jb8t0b1f1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_PkmsxduB9rYVCPaA_A_xFxilzu5Kt5E',
    appId: '1:667537455051:web:b99c4e7870f27b89f9a84e',
    messagingSenderId: '667537455051',
    projectId: 'tp3-420-5n6',
    authDomain: 'tp3-420-5n6.firebaseapp.com',
    storageBucket: 'tp3-420-5n6.appspot.com',
  );

}